"""
Word list for Wordle. Organized by word length (5-8 letters).
All words are lowercase. The game logic normalizes case.
"""

WORDS_BY_LENGTH: dict[int, list[str]] = {
    5: [
        "crane", "slate", "audio", "store", "proud", "light", "flame", "grape",
        "blame", "close", "drive", "phone", "table", "money", "power", "water",
        "party", "heart", "smile", "glass", "night", "peace", "truth", "stone",
        "black", "white", "green", "brain", "sword", "horse", "bread", "cloud",
        "crown", "dance", "early", "earth", "field", "giant", "guide", "happy",
        "house", "level", "magic", "major", "match", "metal", "model", "music",
        "novel", "order", "paper", "place", "plain", "plant", "raise", "river",
        "rough", "round", "route", "scale", "scene", "score", "sharp", "shelf",
        "shift", "shine", "shock", "sight", "since", "skill", "sleep", "slide",
        "slope", "smart", "smell", "smoke", "snake", "solid", "sound", "south",
        "space", "spare", "spark", "speak", "speed", "spend", "sport", "squad",
        "staff", "stage", "stair", "stand", "start", "state", "steam", "steel",
        "stick", "still", "stock", "storm", "story", "stove", "straw", "strip",
        "stuck", "style", "sugar", "sunny", "super", "surge", "swear", "sweep",
        "sweet", "swift", "thick", "thing", "think", "throw", "tight", "timer",
        "tired", "toast", "touch", "tough", "tower", "trace", "track", "trade",
        "trail", "train", "trait", "trash", "treat", "trial", "trick", "troop",
        "trout", "truck", "trunk", "trust", "twist", "ultra", "under", "unite",
        "until", "usage", "usual", "vague", "valid", "value", "vapor", "vault",
        "viral", "virus", "visit", "vital", "vivid", "vocal", "voice", "voter",
        "waste", "watch", "weary", "wedge", "weigh", "wheel", "where", "while",
        "which", "whose", "witch", "woman", "world", "worry", "worse", "worst",
        "worth", "would", "wound", "wrath", "wrong", "yacht", "yield", "young",
        "youth", "zebra", "arise", "avoid", "basis", "catch", "clear", "count",
        "cross", "doubt", "drink", "event", "exist", "extra", "faith", "false",
        "fewer", "final", "first", "front", "given", "grace", "grade", "grant",
        "grasp", "grave", "great", "greet", "grief", "gross", "group", "grown",
        "guess", "guest", "guild", "guilt", "guise", "haunt", "began", "below",
        "blend", "blaze", "bleed", "blink", "block", "blood", "bloom", "blown",
        "board", "boast", "boost", "bound", "boxer", "brave", "break", "breed",
        "brief", "brisk", "broth", "bring", "broad", "broom", "brown", "brush",
        "build", "built", "bunch", "burst", "buyer", "cabin", "cable", "camel",
        "candy", "carry", "cause", "cedar", "chain", "chair", "chalk", "chaos",
        "chase", "cheap", "check", "cheek", "cheer", "chess", "chest", "chick",
        "chief", "child", "chill", "china", "choir", "chord", "civic", "civil",
        "claim", "clamp", "clasp", "class", "clean", "clerk", "click", "cliff",
        "climb", "cling", "clock", "clone", "cloth", "coach", "coast", "color",
        "comet", "comic", "comma", "coral", "creek", "creep", "crest", "crime",
        "crimp", "crisp", "crust", "cubby", "cubic", "curve", "cycle", "dairy",
        "debug", "decoy", "delay", "delta", "depot", "depth", "derby", "dirty",
        "disco", "ditty", "ditch", "dizzy", "dodge", "doing", "donor", "donut",
        "dowel", "draft", "drain", "drape", "drawn", "droop", "drove", "drown",
        "dryer", "dunce", "dwarf", "eagle", "easel", "eight", "elder", "elite",
        "ember", "empty", "enact", "ended", "enemy", "entry", "equal", "error",
        "essay", "every", "exact", "excel", "exile", "expel", "eyelid", "fable",
        "facet", "feast", "fetch", "fever", "fiber", "flair", "flash", "flask",
        "flaw", "fleck", "fleet", "flesh", "flint", "float", "flock", "flood",
        "floor", "floss", "flour", "fluid", "flunk", "flute", "focal", "force",
        "forge", "forth", "forum", "found", "frail", "frame", "frank", "fraud",
        "freak", "fresh", "friar", "froth", "froze", "fruit", "fully", "fungi",
        "funky", "funny", "gamer", "gauze", "gavel", "gecko", "geeky", "ghost",
        "glare", "glaze", "gleam", "glide", "gloom", "gloss", "glove", "glyph",
        "gnome", "going", "gorge", "gourd", "inbox", "index", "joker", "joust",
        "judge", "juice", "juicy", "knack", "kneel", "knife", "knock", "known",
        "label", "lance", "large", "laser", "latch", "later", "laugh", "layer",
        "leach", "learn", "lease", "least", "leave", "lemon", "liege", "liner",
        "liver", "lodge", "login", "lofty", "loose", "lower", "loyal", "lucky",
        "lunar", "lunge", "lusty", "latch", "mayor", "melon", "mercy", "merge",
        "merry", "messy", "micro", "might", "mince", "mirth", "mixer", "mocha",
        "mogul", "moist", "moldy", "month", "moose", "mount", "mouse", "mouth",
        "movie", "murky", "naval", "nerdy", "noble", "noise", "north", "noted",
        "nurse", "nymph", "occur", "ocean", "olive", "onion", "onset", "opted",
        "orbit", "overt", "oxide", "ozone", "padre", "paint", "panda", "pansy",
        "panel", "panic", "patio", "pause", "peach", "penal", "penny", "perch",
        "phase", "piano", "pixel", "pixie", "pizza", "plaid", "plane", "plank",
        "plaza", "pluck", "plumb", "plume", "plump", "plunk", "plush", "poach",
        "point", "poker", "polar", "polka", "pouch", "pound", "prank", "press",
        "price", "prick", "prime", "print", "prior", "prism", "probe", "prone",
        "prose", "prove", "prowl", "proxy", "prude", "prune", "pudgy", "pulse",
        "punch", "pupil", "purge", "queen", "query", "quick", "quiet", "quota",
        "quote", "rabbi", "radar", "radio", "raven", "reach", "ready", "realm",
        "rebel", "reign", "relax", "remix", "repay", "risky", "rival", "riven",
        "roast", "robin", "robot", "rocky", "rogue", "rouse", "rowdy", "ruler",
        "runny", "rural", "rusty", "sadly", "saint", "salty", "salve", "sandy",
        "sauce", "sauna", "scalp", "scamp", "scary", "scold", "scope", "score",
        "scout", "screw", "scrub", "sedan", "seize", "serve", "seven", "sewer",
        "shack", "shade", "shady", "shake", "shaky", "shale", "shall", "shame",
        "shape", "share", "shark", "shear", "sheen", "sheer", "sheet", "shell",
        "sherd", "shiny", "shirt", "shone", "shoot", "shore", "short", "shout",
        "shove", "shown", "shrub", "shrug", "shunt", "siege", "siren", "sixth",
        "sixty", "sized", "skimp", "skipper", "skirt", "skunk", "skull", "slain",
        "slant", "slash", "slave", "sleek", "sleet", "slept", "slick", "slime",
        "sling", "slink", "sloop", "slosh", "slump", "slunk", "snarl", "sneak",
        "sneer", "snide", "sniff", "snout", "snuck", "solar", "sonar", "sonic",
        "sorry", "spade", "spawn", "spell", "spill", "spine", "spite", "splat",
        "split", "spoil", "spook", "spoon", "spore", "spray", "spree", "sprig",
        "spunk", "spurn", "spurt", "stale", "stalk", "stall", "stamp", "stank",
        "stark", "stash", "steal", "steer", "stern", "stoop", "stomp", "stork",
        "stout", "strut", "strafe", "suckle", "sully", "summon", "swamp", "swirl",
        "swoop", "talon", "tango", "tapir", "taunt", "tawny", "taxis", "tense",
        "tenth", "tepid", "terse", "theft", "theism", "three", "threw", "thud",
        "thump", "tiara", "tithe", "toady", "topaz", "toxic", "track", "tramp",
        "trawl", "trend", "trump", "tumor", "tuner", "tunic", "turbo", "twerk",
        "twice", "twixt", "typed", "ulcer", "upset", "urban", "usher", "utter",
        "valve", "vaunt", "vicar", "vigil", "villa", "vinyl", "viper", "virgo",
        "visor", "vixen", "vodka", "vomit", "vying", "wacky", "waltz", "warty",
        "waver", "waxen", "weave", "wedgy", "whelp", "whiff", "whirl", "whisk",
        "wispy", "wormy", "xenon",
    ],
    6: [
        "castle", "bridge", "garden", "forest", "mirror", "puzzle", "silver",
        "rocket", "flight", "basket", "candle", "dragon", "empire", "frozen",
        "gather", "humble", "jungle", "knight", "noodle", "outlet", "pickle",
        "rabbit", "saddle", "tackle", "victor", "wander", "yellow", "zipper",
        "planet", "flower", "stream", "bottle", "circle", "button", "camera",
        "center", "change", "charge", "choice", "church", "client", "coffee",
        "column", "combat", "common", "corner", "cotton", "course", "cousin",
        "create", "credit", "damage", "dancer", "danger", "debate", "desert",
        "detail", "device", "dinner", "donkey", "double", "drawer", "effect",
        "effort", "engine", "escape", "excuse", "expert", "famine", "farmer",
        "father", "figure", "filter", "finger", "finish", "formal", "friend",
        "future", "gentle", "global", "golden", "growth", "guitar", "handle",
        "harbor", "happen", "health", "hidden", "impact", "inform", "insult",
        "island", "itself", "jacket", "launch", "layout", "leader", "letter",
        "little", "longer", "market", "master", "matter", "member", "mental",
        "mister", "modern", "module", "moment", "monkey", "mother", "motion",
        "murder", "narrow", "nation", "notice", "number", "object", "office",
        "option", "orange", "output", "pardon", "parent", "people", "person",
        "player", "pocket", "polish", "pretty", "prince", "profit", "proper",
        "public", "random", "reason", "recent", "record", "reduce", "region",
        "render", "repair", "repeat", "report", "result", "return", "reveal",
        "review", "reward", "ribbon", "rising", "robust", "roller", "rustic",
        "season", "second", "sector", "select", "seller", "settle", "shadow",
        "signal", "simple", "single", "sketch", "slight", "smooth", "sorrow",
        "source", "spirit", "spread", "square", "stable", "static", "status",
        "string", "strong", "stupid", "submit", "sunset", "supply", "system",
        "target", "theory", "thread", "throne", "ticket", "timing", "toggle",
        "tomato", "tunnel", "turret", "typing", "unable", "unpack", "update",
        "useful", "valley", "vendor", "victim", "violet", "visual", "volume",
        "warden", "wealth", "weight", "window", "winner", "winter", "wisdom",
        "wonder", "worker", "worthy", "absent", "absorb", "accent", "access",
        "accord", "across", "active", "actual", "admire", "admits", "afford",
        "afraid", "agenda", "agreed", "allege", "almost", "alpine", "always",
        "ambush", "amount", "animal", "annual", "answer", "antler", "anvil",
        "anyone", "anyway", "arcade", "artful", "artist", "asking", "aspect",
        "assure", "attach", "attain", "attend", "attest", "august", "author",
        "autumn", "avatar", "avenue", "bakery", "ballot", "bandit", "banner",
        "barrel", "battle", "beacon", "beauty", "became", "before", "behalf",
        "behind", "belief", "belong", "beside", "better", "beyond", "bishop",
        "blight", "blouse", "blueprint", "border", "borrow", "bounce", "branch",
        "brawny", "breach", "breast", "breeze", "bridal", "bright", "broken",
        "bronze", "bucket", "budget", "buffet", "bumble", "bundle", "burden",
        "bureau", "burrow", "cactus", "canvas", "carpet", "carton", "census",
        "chance", "chapel", "cheese", "cherry", "chisel", "chrome", "cipher",
        "climax", "closed", "closet", "cobalt", "cobble", "copper", "couple",
        "crater", "debris", "decent", "decide", "decode", "defeat", "defend",
        "delight", "detect", "dialog", "differ", "direct", "divide", "dollar",
        "domain", "donuts", "dotted", "driven", "eleven", "emblem", "employ",
        "endure", "energy", "entail", "entire", "equals", "erupt", "ethics",
        "exceed", "excite", "exempt", "expand", "expect", "export", "extend",
        "fabric", "fading", "fallen", "famous", "feline", "fellow", "female",
        "fender", "fierce", "filling", "fiscal", "fixate", "flickr", "flinch",
        "floret", "format", "foster", "fourth", "freely", "fright", "fringe",
        "galaxy", "gamble", "garlic", "garner", "gender", "getter", "gifted",
        "glance", "glitch", "global", "gluten", "goblin", "gossip", "gravel",
        "grieve", "grille", "gritty", "grovel", "groove", "glossy", "hunter",
        "hybrid", "hyphen", "ignore", "immune", "import", "impose", "income",
        "indeed", "indigo", "indoor", "infant", "inject", "insane", "insect",
        "intact", "intend", "invest", "invoke", "jester", "jogger", "jumble",
        "junior", "junkyard", "kernel", "kitten", "lagoon", "lament", "latent",
        "latter", "legend", "lively", "lizard", "locker", "lonely", "losing",
        "lounge", "lowest", "lumber", "magnet", "maiden", "manage", "mangle",
        "marble", "margin", "maroon", "mascot", "meadow", "meddle", "medium",
        "meteor", "method", "midday", "mighty", "modest", "molten", "mortal",
        "mosaic", "mostly", "moving", "museum", "mutual", "mystic", "naught",
        "nearby", "needle", "neither", "neural", "newbie", "nimble", "ninety",
        "nocturn", "nomad", "nudge", "obsess", "obtain", "offend", "online",
        "oppose", "oracle", "outfit", "outrun", "overdo", "oyster", "paddle",
        "palace", "palace", "pamper", "parcel", "parish", "partly", "patent",
        "pebble", "pencil", "phrase", "pillar", "pirate", "plague", "plains",
        "plaque", "plural", "poetry", "portal", "posted", "potion", "potter",
        "powder", "prefer", "preset", "primal", "prison", "prompt", "proven",
        "puzzle", "radial", "radius", "ranger", "rascal", "rattle", "ravine",
        "refine", "reform", "refuge", "regime", "reject", "remote", "render",
        "rescue", "resent", "resist", "revolt", "riddle", "ritual", "robust",
        "ruckus", "rugged", "rumble", "runoff", "safely", "salmon", "sample",
        "savage", "savant", "saving", "scalar", "sentry", "sermon", "severe",
        "silver", "simmer", "siphon", "sister", "sketch", "skewer", "sleuth",
        "slight", "sludge", "slumber", "smirk", "smudge", "snitch", "socket",
        "soften", "soften", "spanner", "sparse", "spiral", "splice", "spoken",
        "sponge", "sprout", "sprite", "squash", "squeak", "squeal", "squire",
        "strafe", "strung", "studio", "subdue", "subtle", "sultan", "summer",
        "summit", "sundry", "swivel", "syringe", "tablet", "talker", "tamper",
        "tangle", "teapot", "temple", "tender", "tether", "timber", "tingle",
        "tissue", "toggle", "toucan", "trader", "trench", "trophy", "tundra",
        "turban", "turnip", "twitch", "typhon", "unbind", "unfurl", "unique",
        "unlock", "uplift", "upward", "urgent", "utmost", "vacuum", "vanish",
        "vaults", "velvet", "versus", "vessel", "viable", "virtue", "voiced",
        "vortex", "waddle", "walker", "wallet", "walrus", "warder", "waylay",
        "welder", "whales", "wicket", "widely", "widget", "wiggle", "willow",
        "within", "wobble", "wraith", "wrist", "yeoman", "zealot",
    ],
    7: [
        "balance", "blanket", "captain", "courage", "dynamic", "element",
        "fantasy", "graphic", "history", "inspire", "juniper", "kitchen",
        "lantern", "machine", "network", "opinion", "pattern", "quarter",
        "rainbow", "sibling", "tantrum", "uniform", "village", "warrior",
        "weather", "capable", "cabinet", "channel", "chapter", "circuit",
        "classic", "collect", "combine", "comfort", "complex", "concern",
        "confirm", "connect", "contain", "contest", "context", "control",
        "convert", "correct", "counsel", "country", "creator", "culture",
        "current", "decline", "default", "defense", "deliver", "density",
        "despite", "develop", "digital", "disease", "display", "distant",
        "dolphin", "earning", "economy", "emotion", "endless", "enforce",
        "enhance", "episode", "evident", "examine", "example", "exclude",
        "execute", "explore", "express", "extreme", "failure", "fashion",
        "feature", "feeling", "foreign", "formula", "forward", "freedom",
        "general", "genetic", "gesture", "greater", "habitat", "handler",
        "harvest", "healthy", "helpful", "highway", "himself", "horizon",
        "hundred", "imagine", "improve", "include", "initial", "install",
        "instead", "integer", "involve", "journey", "justice", "knowing",
        "landing", "largest", "lasting", "leading", "learned", "library",
        "located", "logical", "manager", "maximum", "meaning", "medical",
        "message", "million", "minimal", "mission", "mixture", "morning",
        "natural", "nothing", "notable", "obvious", "officer", "organic",
        "outline", "outside", "painful", "painter", "partial", "passage",
        "patient", "perfect", "picture", "plastic", "popular", "portion",
        "possess", "present", "process", "product", "project", "promise",
        "protect", "provide", "purpose", "quality", "quickly", "reading",
        "reality", "receive", "regular", "release", "replace", "request",
        "respect", "restore", "revenue", "reverse", "running", "science",
        "section", "servant", "service", "setting", "several", "silence",
        "similar", "soldier", "someone", "speaker", "special", "station",
        "storage", "student", "subject", "success", "suggest", "summary",
        "support", "surface", "survive", "suspect", "teacher", "testing",
        "thought", "through", "tonight", "towards", "traffic", "trouble",
        "turning", "typical", "unknown", "unusual", "usually", "variety",
        "version", "virtual", "visible", "warning", "website", "whether",
        "without", "working", "written", "absolve", "acclaim", "accused",
        "achieve", "acquire", "address", "advance", "adverse", "affable",
        "affixed", "agitate", "alarmed", "alcohol", "alleged", "allergy",
        "allowed", "altered", "amazing", "ancient", "another", "anxiety",
        "applied", "approve", "arrange", "arsenal", "artwork", "assault",
        "athlete", "attempt", "attract", "audible", "augment", "awesome",
        "awkward", "balcony", "bandage", "bargain", "barrier", "battery",
        "bedside", "between", "bizarre", "blossom", "blunder", "boarder",
        "booking", "boolean", "bracket", "brigade", "brother", "browser",
        "bullpen", "buoyant", "burgeon", "busiest", "cabinet", "capsule",
        "caption", "cartoon", "cascade", "catalog", "ceiling", "certify",
        "charade", "chaotic", "charter", "chassis", "cheerup", "chimney",
        "clarity", "cleared", "climate", "cluster", "cockpit", "coconut",
        "cognate", "coldest", "colonel", "compare", "compact", "compass",
        "compile", "compete", "compose", "conceal", "conduct", "confuse",
        "consult", "consult", "corrupt", "courier", "cowling", "crackle",
        "cramped", "crusade", "crystal", "curious", "curtain", "cutting",
        "darling", "darling", "daylong", "daytime", "devoted", "diagram",
        "dialect", "diamond", "dilemma", "discuss", "dismiss", "disrupt",
        "diverse", "divert", "divorce", "dormant", "drastic", "drawing",
        "elastic", "element", "embassy", "emerald", "empower", "enclose",
        "endorse", "enforce", "engaged", "enhance", "entitle", "eternal",
        "evacuate", "evolved", "exactly", "excerpt", "expense", "eyebrow",
        "factory", "fallout", "fanatic", "fatigue", "fertile", "feisty",
        "fiction", "fifteen", "fighter", "filling", "finance", "finding",
        "fitness", "flatbed", "flatten", "flicker", "forward", "frantic",
        "freedom", "freezer", "frequent", "frowning", "fulfill", "further",
        "gateway", "genuine", "gifting", "glacier", "glimpse", "globule",
        "glorify", "glowing", "graduate", "granted", "growing", "grapple",
        "graving", "gravity", "greatly", "grizzly", "grocery", "groping",
        "grounds", "habitat", "halfway", "hallway", "harmony", "hastily",
        "hearing", "heavily", "helping", "heroine", "highway", "history",
        "honesty", "however", "inquiry", "insight", "inspire", "instant",
        "integer", "intense", "justify", "keynote", "kinetic", "kingdom",
        "largely", "layered", "leading", "lengthy", "limited", "linking",
        "listing", "loyalty", "machine", "mapping", "maximum", "measure",
        "medieval", "meeting", "mention", "mindset", "mineral", "minute",
        "missile", "massive", "monitor", "mortise", "nervous", "neutral",
        "nominal", "nucleus", "numeric", "objects", "observe", "offense",
        "offload", "ongoing", "optical", "orchard", "outcome", "outpost",
        "overlap", "overrun", "oversaw", "palette", "panther", "parking",
        "pastime", "pathway", "pattern", "payload", "pension", "perform",
        "phantom", "picking", "pilgrim", "pinhole", "pioneer", "plateau",
        "playing", "premium", "prepare", "primary", "promote", "publish",
        "rapidly", "rebuild", "receipt", "recruit", "refined", "refresh",
        "related", "relaxed", "reliant", "remark", "removal", "renewed",
        "resolve", "results", "retired", "retreat", "returns", "revived",
        "revolve", "rowboat", "sabbath", "scholar", "scrappy", "seagull",
        "segment", "sensory", "shelter", "sheriff", "showing", "signage",
        "skeletal", "skilled", "skyline", "smoking", "smuggle", "snapper",
        "society", "somehow", "sorcery", "sorting", "spacing", "sparked",
        "species", "specify", "spilled", "spindle", "spirits", "squalid",
        "squeeze", "sterile", "storage", "studied", "stumble", "surgeon",
        "swallow", "sweeper", "tactics", "tallest", "tariffs", "thermal",
        "thunder", "tipping", "topmost", "torrent", "tractor", "transit",
        "trilogy", "triumph", "trumpet", "trusted", "turnout", "twisted",
        "uncover", "undergo", "unicorn", "updated", "upgrade", "uptight",
        "useless", "utility", "vaccine", "veteran", "village", "villain",
        "voltage", "vulture", "watcher", "welfare", "whisper", "whoever",
        "wildcat", "windows", "wishful", "witness", "wrestle", "writers",
    ],
    8: [
        "absolute", "backbone", "calendar", "database", "eventual", "faithful",
        "gathered", "headline", "innocent", "jealousy", "keyboard", "language",
        "magazine", "negative", "operator", "peaceful", "quantity", "resource",
        "standard", "terminal", "ultimate", "variable", "wanderer", "yearning",
        "backyard", "baseball", "birthday", "careless", "clothing", "describe",
        "disagree", "download", "employee", "equation", "existing", "familiar",
        "flagship", "football", "generous", "grateful", "hardware", "hospital",
        "increase", "interest", "involved", "judgment", "medicine", "movement",
        "national", "notebook", "organize", "platform", "practice", "progress",
        "question", "reliable", "response", "schedule", "security", "software",
        "solution", "specific", "strength", "supplies", "thousand", "together",
        "training", "transfer", "umbrella", "universe", "validate", "valuable",
        "violence", "whatever", "whenever", "wherever", "yourself", "complete",
        "consider", "continue", "contract", "contrast", "convince", "creation",
        "creature", "customer", "decision", "discover", "distance", "dominant",
        "dramatic", "duration", "economic", "educated", "election", "electric",
        "everyone", "exchange", "exercise", "external", "finances", "followed",
        "function", "generate", "globally", "guidance", "happened", "heritage",
        "identify", "industry", "informal", "instance", "internal", "internet",
        "isolated", "lifetime", "likewise", "location", "moreover", "multiple",
        "musician", "navigate", "normally", "occurred", "offering", "official",
        "opposite", "overcome", "physical", "planning", "position", "possible",
        "previous", "probable", "produces", "proposal", "protocol", "purchase",
        "recently", "recorded", "redirect", "regional", "remained", "remember",
        "removing", "replaced", "research", "revealed", "reviewed", "sequence",
        "settings", "situated", "skeleton", "sleeping", "slightly", "speaking",
        "spending", "standing", "starting", "strategy", "strongly", "struggle",
        "studying", "suddenly", "suitable", "surgical", "survived", "teachers",
        "template", "thinking", "timeline", "tracking", "troubled", "turnover",
        "uniquely", "updating", "utilized", "vacation", "wildfire", "withdraw",
        "workshop", "absorbed", "abstract", "academic", "accessed", "accident",
        "accurate", "achieved", "acquired", "actually", "addition", "adequate",
        "adjusted", "admitted", "advanced", "advocate", "affected", "affluent",
        "afforded", "agitated", "animated", "annually", "answered", "apparent",
        "appealed", "approved", "argument", "arranged", "assigned", "assisted",
        "attached", "attacked", "attained", "attended", "attitude", "auditing",
        "balanced", "betrayal", "bracelet", "breaking", "bringing", "business",
        "captured", "cerebral", "champion", "changing", "chapters", "circular",
        "citizens", "climbing", "coherent", "cohesive", "collapse", "colonial",
        "combined", "commence", "competed", "compiled", "compiled", "confined",
        "conflict", "congress", "connected", "constant", "consumed", "contains",
        "converts", "corrects", "coverage", "crossing", "cultural", "curtains",
        "deadline", "deceived", "defining", "delicate", "demanded", "depicted",
        "designed", "detailed", "detected", "devoting", "dialogue", "directed",
        "disabled", "disaster", "domestic", "enormous", "entering", "entrance",
        "envelope", "equality", "entirely", "escaping", "estimate", "evaluate",
        "evidence", "evolving", "examined", "executed", "extended", "featured",
        "feedback", "fighting", "finished", "flagship", "flexible", "focusing",
        "followed", "forecast", "forested", "founding", "fraction", "fragment",
        "frequent", "friendly", "frontier", "garlands", "gathered", "gladness",
        "gleaming", "gorgeous", "graphite", "grateful", "guardian", "handsome",
        "hapless", "hardship", "harmonic", "headlong", "highland", "historic",
        "homeless", "humanist", "hundreds", "imagined", "imported", "improved",
        "included", "informed", "inhabit", "inspired", "intended", "invested",
        "isolated", "kinship", "landmark", "learning", "licensed", "lifelong",
        "limiting", "listened", "manifest", "mastered", "matching", "material",
        "measured", "medieval", "memories", "mentally", "minority", "mistakes",
        "modestly", "mountain", "negative", "notebook", "obtained", "occurred",
        "outright", "overcome", "overlook", "overtime", "painting", "paradise",
        "patience", "peaceful", "personal", "physical", "polished", "powerful",
        "precious", "prepared", "provided", "publicly", "realized", "received",
        "reformed", "regarded", "relieved", "rendered", "repeated", "required",
        "resisted", "resolved", "returned", "revealed", "reviewed", "rewarded",
        "rightful", "rigorous", "romantic", "rotating", "roundtable", "safeguard",
        "seasonal", "secretly", "selected", "sensible", "separate", "severely",
        "showcase", "sideline", "signaled", "singular", "smallest", "spectrum",
        "splendid", "spotless", "steadily", "stepwise", "sterling", "stubborn",
        "sturdily", "superior", "sympathy", "thankful", "thriving", "together",
        "tomorrow", "touching", "traveled", "treasury", "trustful", "unbended",
        "unbroken", "underpin", "unfasten", "unmarked", "unravel", "untangle",
        "upcoming", "updating", "vanguard", "verified", "versions", "vigilant",
        "visually", "volcanic", "wealthier", "welcomed", "wholesome", "wireless",
        "woodland", "writings", "yearlong", "zealously",
    ],
}

# Flat set of all valid words for O(1) lookup
ALL_WORDS: set[str] = {
    word.upper()
    for words in WORDS_BY_LENGTH.values()
    for word in words
}


def get_words_for_length(length: int) -> list[str]:
    """Return all words of the given length (uppercase)."""
    return [w.upper() for w in WORDS_BY_LENGTH.get(length, [])]


def is_valid_word(word: str, length: int) -> bool:
    """Check if a word is in the valid word list for the given length."""
    return word.upper() in {w.upper() for w in WORDS_BY_LENGTH.get(length, [])}
